"""Unit tests for LogWriter."""

from os import listdir, remove
from os.path import isfile, join

from uuid import uuid4
from log_manager.log_writer import LogWriter
from log_manager.log_reader import LogReader
import config

# Prefix for files generated by this function
TEST_ID = str(uuid4())
HEADER = ["X", "Y", "pew"]


def test_writer_basic():
    """Basic test for LogWriter class."""
    lw1 = LogWriter(header=HEADER, prefix=TEST_ID)

    dict_to_write = {}
    dict_to_write["X"] = 10
    dict_to_write["pew"] = "pew"
    dict_to_write["Y"] = 20

    lw1.write_line(dict_to_write)
    lw1.write_line(dict_to_write)


def test_prefix_handling():
    """Test prefix validation for LogWriter."""
    # Invalid tab character
    catch_err_1 = False
    try:
        _ = LogWriter(header=["test"], prefix="\test")
    except AttributeError:
        catch_err_1 = True

    assert catch_err_1

    # Invalid backslash
    catch_err_2 = False
    try:
        _ = LogWriter(header=["test"], prefix="/test")
    except AttributeError:
        catch_err_2 = True
    assert catch_err_2

    # Invalid dot character
    catch_err_3 = False
    try:
        _ = LogWriter(header=["test"], prefix=".test")
    except AttributeError:
        catch_err_3 = True
    assert catch_err_3


def test_header_validation():
    """Test logic for checking header."""
    catch_err = False
    try:
        _ = LogWriter(header=[])
    except AttributeError:
        catch_err = True

    assert catch_err


def test_reader_basic():
    log_reader = LogReader(prefix=TEST_ID)

    # We have found a file
    assert len(log_reader.files)
    # It matches the header we use
    assert log_reader.header == HEADER
    # The data has the same number of columns
    assert len(log_reader.data) == len(HEADER)


def test_reader_data():
    lw_invalid = LogWriter(header=HEADER + ["pew2"], prefix=TEST_ID)
    dict_to_write = {}
    dict_to_write["X"] = 10
    dict_to_write["pew"] = "pew"
    dict_to_write["pew2"] = "pew2"
    dict_to_write["Y"] = 20
    lw_invalid.write_line(dict_to_write)
    lw_invalid.write_line(dict_to_write)

    log_reader = LogReader(prefix=TEST_ID)
    log_reader.read_data()

    assert len(log_reader.data["X"]) == 2
    assert len(log_reader.data["Y"]) == 2
    assert len(log_reader.data["pew"]) == 2


def cleanup():
    """Clean up logs for this run."""
    log_files = [join(config.LOG_DIR, f) for f in listdir(config.LOG_DIR)
                 if isfile(join(config.LOG_DIR, f))]
    for file_ in log_files:
        if TEST_ID in file_:
            remove(file_)


# Run writer test cases
test_writer_basic()
test_prefix_handling()
test_header_validation()

# Run reader test cases
test_reader_basic()
test_reader_data()

cleanup()
